global:
  scrape_interval: 15s

rule_files:
  - 'etc/prometheus/recording_rules.yml'

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "portfolio-dev"
    metrics_path: /metrics
    static_configs:
      - targets: ["portfolio-dev:3000"]
